# Generated by Django 4.1.7 on 2023-02-27 00:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillSmell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('weight', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BillTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('sort_priority', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BillTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('weight', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gov', models.CharField(max_length=8, verbose_name='Government')),
                ('gov_id', models.CharField(max_length=1000, verbose_name="Bill's Government Identifier")),
                ('title', models.TextField()),
                ('text', models.TextField()),
                ('type', models.CharField(max_length=50)),
                ('html', models.TextField()),
                ('date', models.DateField()),
                ('last_analyzed_at', models.DateTimeField(default=None)),
                ('smelliness', models.IntegerField(default=None, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('smells', models.ManyToManyField(to='govscentdotorg.billsmell')),
                ('tags', models.ManyToManyField(to='govscentdotorg.billtags')),
                ('text_topics', models.ManyToManyField(related_name='text_topics', to='govscentdotorg.billtopic')),
                ('title_topics', models.ManyToManyField(related_name='title_topics', to='govscentdotorg.billtopic')),
            ],
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['gov_id'], name='govscentdot_gov_id_95306a_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['date'], name='govscentdot_date_18db25_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['last_analyzed_at'], name='govscentdot_last_an_c732fb_idx'),
        ),
    ]
