# Generated by Django 4.1.7 on 2023-02-27 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govscentdotorg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='last_analyzed_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
