# Generated by Django 4.1.7 on 2023-02-27 00:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govscentdotorg', '0002_alter_bill_last_analyzed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='smelliness',
            field=models.IntegerField(default=None, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='bill',
            name='smells',
            field=models.ManyToManyField(null=True, to='govscentdotorg.billsmell'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='tags',
            field=models.ManyToManyField(null=True, to='govscentdotorg.billtags'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='text_topics',
            field=models.ManyToManyField(null=True, related_name='text_topics', to='govscentdotorg.billtopic'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='title_topics',
            field=models.ManyToManyField(null=True, related_name='title_topics', to='govscentdotorg.billtopic'),
        ),
    ]
