# Generated by Django 4.1.7 on 2023-03-05 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govscentdotorg', '0005_alter_bill_unique_together_remove_bill_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='bill',
            name='html',
            field=models.TextField(default=''),
        ),
    ]
