# Generated by Django 4.1.7 on 2023-03-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govscentdotorg', '0006_bill_text_alter_bill_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='gov_group_id',
            field=models.CharField(blank=True, null=True, default=None, help_text='Can be used to group a bill across many versions.', max_length=1000, verbose_name='Bill Group Identifier'),
        ),
        migrations.AddField(
            model_name='bill',
            name='is_latest_revision',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bill',
            name='gov_id',
            field=models.CharField(help_text='Each revision of bill has its own gov_id.', max_length=1000, verbose_name='Bill Identifier'),
        ),
        migrations.AlterField(
            model_name='billtopic',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['gov', 'gov_group_id'], name='govscentdot_gov_8cc3fc_idx'),
        ),
    ]
