# Generated by Django 4.1.7 on 2023-03-19 20:30

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govscentdotorg', '0007_bill_gov_group_id_bill_is_latest_revision_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='billtopic',
            name='weight',
        ),
        migrations.AddField(
            model_name='bill',
            name='on_topic_ranking',
            field=models.PositiveSmallIntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='bill',
            name='smelliness',
            field=models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='billtopic',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['last_analyzed_at', 'is_latest_revision'], name='govscentdot_last_an_d73886_idx'),
        ),
        migrations.DeleteModel(
            name='BillTags',
        ),
    ]
