# Generated by Django 4.1.7 on 2023-03-19 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govscentdotorg', '0008_remove_bill_tags_remove_billtopic_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billtopic',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
