# Generated by Django 4.1.7 on 2023-03-19 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govscentdotorg', '0010_bill_last_analyze_error_bill_last_analyze_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='on_topic_reasoning',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
