# Generated by Django 4.1.7 on 2023-03-19 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govscentdotorg', '0011_bill_on_topic_reasoning'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='text_topics',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='title_topics',
        ),
        migrations.AddField(
            model_name='bill',
            name='topics',
            field=models.ManyToManyField(related_name='topics', to='govscentdotorg.billtopic'),
        ),
    ]
