# Generated by Django 4.1.7 on 2023-03-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govscentdotorg', '0012_remove_bill_text_topics_remove_bill_title_topics_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['gov', 'date'], name='govscentdot_gov_197d28_idx'),
        ),
    ]
