# Generated by Django 4.1.7 on 2023-03-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govscentdotorg', '0013_bill_govscentdot_gov_197d28_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='source_file_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
