# Generated by Django 4.1.7 on 2023-03-26 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('govscentdotorg', '0015_bill_govscentdot_on_topi_32544f_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='html',
        ),
    ]
