# Generated by Django 4.1.7 on 2023-04-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govscentdotorg', '0016_remove_bill_html'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('last_analyze_error', models.TextField(blank=True, default=None, null=True)),
                ('last_analyze_response', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_sections',
            field=models.ManyToManyField(related_name='sections', to='govscentdotorg.billsection'),
        ),
    ]
