# Generated by Django 4.1.7 on 2023-04-02 18:58

from django.db import migrations


def populate_bill_sections(apps, schema_editor):
    Bill = apps.get_model('govscentdotorg', 'Bill')
    BillSection = apps.get_model('govscentdotorg', 'BillSection')
    bills = Bill.objects.filter(last_analyzed_at__isnull=False).only("gov_id", "bill_sections")
    for bill in bills:
        if bill.bill_sections.all() and len(bill.bill_sections.all()) > 0:  # should never happen but just in case
            continue
        print('Will setup sections.', bill.gov_id)
        sections = []
        section = BillSection(
            text=bill.text,
            last_analyze_error=bill.last_analyze_error,
            last_analyze_response=bill.last_analyze_response,
        )
        section.save()
        sections.append(section)
        bill.bill_sections.set(sections)
        bill.save()


class Migration(migrations.Migration):

    dependencies = [
        ('govscentdotorg', '0017_billsection_bill_bill_sections'),
    ]

    operations = [
        migrations.RunPython(populate_bill_sections),
    ]
