# Generated by Django 4.1.7 on 2023-04-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govscentdotorg', '0018_auto_20230402_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='final_analyze_response',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='last_analyze_model',
            field=models.CharField(default='gpt-3-turbo', max_length=100, null=True),
        ),
    ]
