# Generated by Django 4.1.7 on 2023-04-02 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govscentdotorg', '0019_bill_final_analyze_response_bill_last_analyze_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='billsection',
            name='last_analyze_model',
            field=models.CharField(default='gpt-3-turbo', max_length=100, null=True),
        ),
    ]
